# Setup
title:               'BIGCPA'
tagline:             'Make Money Online'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://ancient-emu.cloudvent.net
baseurl:             ''

# About/contact
author:
  name:              Alex Creio
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

disqus_shortname: bigcpa

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/category/'

collections:
  music:
    name: Моя Музыка
    output: true
  staff:
    name: Люди Staff
    #permalink: 

defaults:
  -
    scope:
      path: ""
      type: 
    values:
      layout:
      
gems:
  - jekyll-paginate
  
markdown: kramdown

excerpt_separator: "<!-- more -->"

# Permalinks
paginate: 2
paginate_path: '/blog/page:num/'
permalink: '/blog/:title/'

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/lp/'
  Blog:           
    - '/blog/'
    - { Тестовая Рубрика: '/blog/category/#test' }
    - { Linux: '/blog/linux/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://codinfox.github.io/'
    
sass:
  style: compressed
  sass_dir: _scss