# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://ancient-emu.cloudvent.net
baseurl:             '/lp'

# About/contact
author:
  name:              Alex Creio
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
markdown: kramdown

excerpt_separator: "<!-- more -->"

# Permalinks
paginate: 5
paginate_path: '/blog/page:num'
permalink: '/:categories/:title/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'