# Setup
title:               'BIGCPA'
description:         'Index description'
tagline:             'Make Money Online'
info:         'Приветсвую! Я — Alex Creio. Специализируюсь на создании и продвижении сайтов, смотрите — <a href="/about/" >Мои Услуги</a>. Также активно занимаюсь арбитражом трафика и интересуюсь Linux, подробнее читайте тут <a href="/about/" >О блоге</a>.'
url:                 http://ancient-emu.cloudvent.net
baseurl:             ''

# About/contact
author:
  name:              Alex Creio
  url:               https://twitter.com/acretm
  email:             mailcreio@gmail.com

disqus_shortname: bigcpa

# collections:
#   category:
#     output: true

# defaults:
#   - scope:
#       path: ""
#       type: category
#     values:
#       layout: category
      
jekyll-archives:
  enabled: 
    - tags
    - categories
  layouts:
    tag: tag
    category: cat
  permalinks:
    tag: '/tag/:name/'
    category: '/cat/:name/'

# Navigation (2nd level links supported)
nav:
    Главнвя:
        - '/blog/'
    Тех. часть:
        - '/cat/jekyll/'
    Продвижение: 
        - '/cat/seo/'
    Делай деньги:
        - '/cat/money/'
    Софт и сервисы:
        - '/cat/partner/'
    Linux: 
        - '/cat/linux/'
    # Категории:           
    #     - '/cat/'
    #     - { Теги: '/tag/' }
    О блоге:          
        - '/whois/'
    Карта блога:          
        - '/tag/'
      
gems:
  - jekyll-paginate
  - jekyll-archives
  
markdown: kramdown

excerpt_separator: "<!--more-->"

# Permalinks
paginate: 3
paginate_path: '/blog/page:num/'
permalink: '/p/:title/'

sass:
  style: compressed
  sass_dir: _scss
  
  
  
  
  
  