# Setup
title:               'BIGCPA'
description:         'Index description'
tagline:             'Make Money Online'
info:         'Приветсвую! Автор блога Alex Creio <a rel="nofollow" href="https://twitter.com/creio" target="_blank">@creio</a>. Мои контакты находятся на странице <a href="/about/" >О блоге</a>, или чат кнопка внизу.'
url:                 http://ancient-emu.cloudvent.net
baseurl:             ''

# About/contact
author:
  name:              Alex Creio
  url:               https://twitter.com/creio
  email:             mailcreio@gmail.com

disqus_shortname: bigcpa

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/category/'

collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category

# Navigation (2nd level links supported)
nav:
    Главнвя:
        - '/blog/'
    Партнерские программы:
        - '/blog/partner/'
    Linux: 
        - '/blog/linux/'
    Продвижение сайта: 
        - '/blog/seo/'
    Jekyll уроки:
        - '/blog/jekyll/'
    # Категории:           
    #     - '/blog/category/'
    #     - { Tags: '/blog/tags/' }
    О блоге:          
        - '/about/'
    Карта блога:          
        - '/blog/category/'
      
gems:
  - jekyll-paginate
  - jekyll-paginate-category
  
markdown: kramdown

excerpt_separator: "<!-- more -->"

# Permalinks
paginate: 2
paginate_path: '/blog/page:num/'
permalink: '/blog/:title/'
category_dir: "/blog/category/"
category_layout: "category.html"

sass:
  style: compressed
  sass_dir: _scss