# Setup
title:               'BIGCPA'
description:         'Index description'
tagline:             'Make Money Online'
info:         'Приветсвую! Автор блога — Alex Creio <a rel="nofollow" href="https://twitter.com/creio" target="_blank">@creio</a>. Мои контакты находятся на странице <a href="/about/" >О блоге</a>, или пишите в чат справа.'
url:                 http://ancient-emu.cloudvent.net
baseurl:             ''

# About/contact
author:
  name:              Alex Creio
  url:               https://twitter.com/creio
  email:             mailcreio@gmail.com

disqus_shortname: bigcpa

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/category/'

collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category

# Navigation (2nd level links supported)
nav:
    Главнвя:
        - '/blog/'
    Тех. часть:
        - '/blog/jekyll/'
    Продвижение: 
        - '/blog/seo/'
    Делай деньги:
        - '/blog/money/'
    Софт и сервисы:
        - '/blog/partner/'
    Linux: 
        - '/blog/linux/'
    # Категории:           
    #     - '/blog/category/'
    #     - { Tags: '/blog/tags/' }
    О блоге:          
        - '/about/'
    Карта блога:          
        - '/blog/category/'
      
gems:
  - jekyll-paginate
  
markdown: kramdown

excerpt_separator: "<!-- more -->"

# Permalinks
paginate: 3
paginate_path: '/blog/page:num/'
permalink: '/blog/:title/'

sass:
  style: compressed
  sass_dir: _scss
  
  
  
  
  
  